before:
  hooks:
    - go mod download

builds:
  - id: "darwin-amd64"
    main: ./cmd/dymd
    binary: dymd
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -tags=cgo netgo ledger
      - -trimpath
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=dymension -X github.com/cosmos/cosmos-sdk/version.AppName=dymd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} -X github.com/tendermint/tendermint/version.TMCoreSemVer=
  - id: "darwin-arm64"
    main: ./cmd/dymd
    binary: dymd
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -tags=cgo netgo ledger
      - -trimpath
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=dymension -X github.com/cosmos/cosmos-sdk/version.AppName=dymd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} -X github.com/tendermint/tendermint/version.TMCoreSemVer=
  - id: "linux-amd64"
    main: ./cmd/dymd
    binary: dymd
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=netgo ledger cgo
      - -trimpath
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=dymension -X github.com/cosmos/cosmos-sdk/version.AppName=dymd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} -X github.com/tendermint/tendermint/version.TMCoreSemVer=
  # - id: "linux-arm64"
  #   main: ./cmd/dymd
  #   binary: dymd
  #   env:
  #     - CGO_ENABLED=1
  #     - CC=aarch64-linux-gnu-gcc
  #     - CXX=aarch64-linux-gnu-g++
  #   goos:
  #     - linux
  #   goarch:
  #     - arm64
  #   flags:
  #     - -tags=cgo
  #   ldflags:
  #     - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=dymension -X github.com/cosmos/cosmos-sdk/version.AppName=dymd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} -X github.com/tendermint/tendermint/version.TMCoreSemVer=

archives:
  # disables archiving; to enable use commented lines below
  - format: binary
    name_template: "{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  
release:
  prerelease: true
  name_template: "v{{.Version}}"

checksum:
  name_template: SHA256SUMS-v{{.Version}}.txt
  algorithm: sha256

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

changelog:
  skip: false