name: E2E Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      # trigger workflow if PR is opened directly as R4R.
      - opened
      # trigger workflow if changes are pushed to the branch.
      - synchronize
      # trigger workflow if PR is marked ready for review.
      - ready_for_review
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'LICENSE'

permissions:
  contents: read
  packages: write

jobs:   
  build-and-push-e2e-image:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push 
        id: build_push_image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          push: true
          platforms: linux/amd64
          tags: |
              ghcr.io/dymensionxyz/dymension:e2e         
  # e2e-tests:
  #   needs: build-and-push-e2e-image
  #   uses: dymensionxyz/e2e-tests/.github/workflows/e2e-test-workflow-call.yml@c1f9835489c49a92828a60d16bafa7e2060e4bf2
  #   with:
  #     dymension_ci: "e2e"
