name: Upgrade Testing

on: 
  push:
    branches: 
      - MasterPi-2124/test-upgrade
    release:
      types: [published]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v2 

    - name: Update code
      run: |
        ls -a
        pwd
        wget https://snapshots.kjnodes.com/dymension/snapshot_latest.tar.lz4
