name: Upgrade Testing

on: 
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v2 

    - name: Update code
      run: |
        echo "hello"
        ip a
        neofetch
