name: Upgrade Testing

on: 
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v2 

    - name: Update code
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIV_KEY }}
        script: |
          echo "hello"
          ip a
          neofetch
